CREATE DATABASE Little_Lemon;
USE Little_Lemon;

CREATE TABLE Customers(
	CustomerID NOT NULL PRIMARY KEY,
	FUllName VARCHAR(100) NOT NULL,
	PhoneNumber INT NOT NULL UNIQUE;
);

CREATE TABLE Bookings ( 
	BookingID INT NOT NULL PRIMARY KEY, 
	BookingDate DATE NOT NULL, 
	TableNumber INT NOT NULL, 
	NumberOfGuests INT NOT NULL CHECK(NumberOfGuests<=8), 
	CustomerID INT NOT NULL, 
	FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID) ON DELETE CASCADE ON UPDATE CASCADE
)